#!/usr/bin/env just --justfile
# ^ A shebang isn't required, but allows a justfile to be executed
#   like a script, with `./justfile test`, for example.

set dotenv-load := true

# default lists actions
default:
  @just -f justfile --list

generate name="test":
  #!/usr/bin/env bash
  set -eufo pipefail
  HYGEN_OVERWRITE=1 npx hygen tailwind new {{ name }} 
  cp -r _templates/tailwind/new/og {{ name }}/og
  cp -r _templates/tailwind/new/favicon.ico {{ name }}/favicon.ico

