#!/usr/bin/env just --justfile
# ^ A shebang isn't required, but allows a justfile to be executed
#   like a script, with `./justfile test`, for example.

set dotenv-load := true

# default lists actions
default:
  @just -f justfile --list

clean:
  rm -rf ./dist || true
  rm -rf ./.parcel-cache || true


clean-all: clean
  rm -rf ./node_modules || true

nix:
  #!/usr/bin/env bash
  set -xeufo pipefail
  nix develop --command zsh
  
install:
  #!/usr/bin/env bash
  set -eufo pipefail
  npm install


test:
  #!/usr/bin/env bash
  set -eufo pipefail
  npm run test

build:
  #!/usr/bin/env bash
  set -eufo pipefail
  npm run build

host:
  #!/usr/bin/env bash
  set -eufo pipefail
  #mkdir -p ./dist/public
  #cp -r ./public ./dist
  npm run start  

  
watch:
  #!/usr/bin/env bash
  set -xeufo pipefail
  watchexec --exts ts npm run test


